### ISSUE TITLE
Failed to read Git log

### ISSUE THREAD

**Issue by webkernel** [rmsubekti/the-roots-home#1]
Hi,
I'd love to use this theme, but every time I try to start hugo server with ExampleSite content I get the following error. I am running latest Hugo extended version with Manjaro Linux.

Failed to read Git log: fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Built in 123 ms
Error: Error building site: logged 1 error(s)

**Comment by bect** [comment]
Comment this line `enableGitInfo=true` in your config.toml 
[like this](https://github.com/rmsubekti/the-roots-home/commit/63539a30dfaabeede31738f8a4e3f63d80513e8e)

Thank you : )

**Comment by webkernel** [comment]
Many thanks! Just a quick question. How can I make archives.md show content?

**Comment by bect** [comment]
this template automatically lists your posts by creating a section page, term page, or taxonomy page.
if you mean to list all your posts on a single page, you could try some of  [these snippets](https://gohugo.io/templates/lists/#group-content).
